2018-06-23 16:25:56,697 ERROR: Exception on /index [GET] [in /home/josh/anaconda3/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/home/josh/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/josh/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/josh/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/josh/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/home/josh/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/josh/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/josh/Documents/Programming/EMR/digital_doc/app/routes.py", line 12, in index
    return render_template('index.html', title='Home', patients=patients)
NameError: name 'patients' is not defined
2018-06-23 16:26:12,082 INFO: Digital doctor [in /home/josh/Documents/Programming/EMR/digital_doc/app/__init__.py:45]
2018-06-23 16:27:00,064 INFO: Digital doctor [in /home/josh/Documents/Programming/EMR/digital_doc/app/__init__.py:45]
2018-06-23 16:28:00,811 INFO: Digital doctor [in /home/josh/Documents/Programming/EMR/digital_doc/app/__init__.py:45]
2018-06-23 16:28:29,234 INFO: Digital doctor [in /home/josh/Documents/Programming/EMR/digital_doc/app/__init__.py:45]
